version: '3'

services:
    web:
        build: ./app
        image: tik2fa-django:latest
        container_name: tik2fa_app
        command: gunicorn app.wsgi:application --bind 0.0.0.0:8000 --workers=2
        volumes:
            - ./app/:/usr/src/app/
            - static_volume:/usr/src/app/static
        expose:
            - 8000
        env_file: 
            - ./.env
        environment: 
            - DJANGO_ALLOWED_HOSTS=*
        restart: unless-stopped
        depends_on: 
            - db
            - celery-redis
    db:
        image: postgres:12.0-alpine
        container_name: tik2fa_db
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file: 
            - ./.env
        environment: 
            - POSTGRES_USER=${SQL_USER}
            - POSTGRES_PASSWORD=${SQL_PASSWORD}
            - POSTGRES_DB=${SQL_DATABASE}
    nginx:
        build: ./nginx
        container_name: tik2fa_nginx
        volumes: 
            - static_volume:/usr/src/app/static
        ports:
            - 80:80
        depends_on:
            - web
    celery-redis:
        image: redis:alpine
        container_name: tik2fa_redis
    celery:
        image: tik2fa-django:latest
        container_name: tik2fa_celery
        command: celery -A app worker -l info --concurrency=4
        volumes:
            - ./app/:/usr/src/app/
        env_file: 
            - ./.env
        environment: 
            - DJANGO_ALLOWED_HOSTS=*
        depends_on:
            - web
            - celery-redis
    celery-beat:
        image: tik2fa-django:latest
        container_name: tik2fa_celery_beat
        command: celery -A app beat -l info
        volumes:
            - ./app/:/usr/src/app/
        env_file: 
            - ./.env
        environment: 
            - DJANGO_ALLOWED_HOSTS=*
        depends_on:
            - web
            - celery-redis
    watcher:
        image: tik2fa-django:latest
        container_name: tik2fa_watcher
        command: python watcher.py
        env_file: 
            - ./.env
        restart: unless-stopped

volumes:
    postgres_data:
    static_volume:
