# Generated by Django 3.0.7 on 2020-08-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('source_ip', models.TextField(blank=True)),
                ('destination_ip', models.TextField(blank=True)),
                ('connected', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('unconfirmed_connections_count', models.IntegerField(default=0)),
                ('last_connection_time', models.DateTimeField()),
            ],
        ),
    ]
