# Generated by Django 3.0.7 on 2020-08-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_last_confirm_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='chat_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
