# Generated by Django 3.0.7 on 2020-08-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20200807_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='caller_id',
            field=models.TextField(blank=True),
        ),
    ]
