# Generated by Django 3.0.7 on 2021-04-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_caller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
