# Generated by Django 4.0.4 on 2022-05-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='chat_id',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
